whisper:
  inference:
    ros__parameters:
      # whisper
      model_name: "tiny.en" # other models https://huggingface.co/ggerganov/whisper.cpp
      wparams:
        language: "en"
        print_progress: true
        n_threads: 7
      cparams:
        flash_attn: true
        gpu_device: 0
        use_gpu: false

      # buffer
      buffer_capacity: 20 # seconds
      callback_ms: 1000 # milliseconds
